// <auto-generated />
namespace CaprisaProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class default21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(default21));
        
        string IMigrationMetadata.Id
        {
            get { return "201604052341247_default21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
